name: pytest-coverage-commentator
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          platform: x64
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov
          if [ -f requirements-tests.txt ]; then pip install -r requirements-tests.txt; fi
      - name: Run tests
        run: |
          pytest --cov="." tests
      # - name: Comment coverage
      #   uses: coroo/pytest-coverage-commentator@v1.0.2
